# 11월 11일 수요일 실습과제

# 카이제곱 검정 ~선형회귀분석

In [55]:
import pandas as pd
import statsmodels.api as sm
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from scipy.stats import shapiro
import statsmodels.formula.api as smf
import seaborn as sns
from scipy import stats
import scipy.stats
from statsmodels.stats.proportion import proportions_ztest
from scipy.stats import chi2_contingency
from statsmodels.stats.anova import anova_lm
from statsmodels.formula.api import ols


%matplotlib inline
matplotlib.rc('font', family='Malgun Gothic')
plt.rc('font', family ='Malgun Gothic')

In [56]:
df = pd.DataFrame({'A':[18,1,8,7,10,9,10], 'B':[8,2,14,5,5,9,4],'C':[4,1,3,4,9,5,4],
                  "D":[4,1,2,3,2,7,3],'E':[3,1,3,1,1,1,1],"F":[3,25,8,10,2,1,7]})

chi, pval, dof, expected = stats.chi2_contingency(df.T)

print("chi-square test")
print("chisq:{0:0.3f}".format(chi))
print("p:{0:0.3f}".format(pval))
print("degree of freedom:{}".format(dof))
print("expected value \n{}".format(expected.round(3)))

# p-value가 유의 수준인 0.5보다 작기때문에 귀무가설을 기각하고 대립가설을 채택
# 즉 제품 A,B,C,D,E,F 별로 차이가 있다.


chi-square test
chisq:98.274
p:0.000
degree of freedom:30
expected value 
[[11.004  8.528 10.454  8.253  7.978  8.803  7.978]
 [ 8.21   6.362  7.799  6.157  5.952  6.568  5.952]
 [ 5.24   4.061  4.978  3.93   3.799  4.192  3.799]
 [ 3.843  2.978  3.651  2.882  2.786  3.074  2.786]
 [ 1.921  1.489  1.825  1.441  1.393  1.537  1.393]
 [ 9.782  7.581  9.293  7.336  7.092  7.825  7.092]]


# One way ANOVA 실습

In [62]:
df = pd.read_csv("/home/piai/bigdata/data/ANOVA.csv",engine='python')
df.head()

formula = 'time ~ gangjong'

lm = smf.ols(formula, df).fit()

print(anova_lm(lm))

#강종별 2차정련 시간을 One way ANOVA로 분석한 결과
#p-value 0.019으로 0.05이하로 강종별로 차이가 있다.


            df      sum_sq    mean_sq         F    PR(>F)
gangjong   3.0  104.603333  34.867778  4.171868  0.019013
Residual  20.0  167.156667   8.357833       NaN       NaN


# 상관분석 실습

In [63]:
df=pd.read_csv("/home/piai/bigdata/data/correaltion.csv", engine ='python')
df.head()

corr, pval = stats.pearsonr(df["temp"],df["strength"])

print("Correiation Analysis")
print("corr: {0:0.3f}".format(corr))
print('p-value : {0:0.3f}'.format(pval))


#쿠키 반죽의 온도와 초코칩 강도는 상관계수인 corr을 보면 -0.899로
#강한 음의 상관관계가 있는것을 확인할 수 있다.


Correiation Analysis
corr: -0.899
p-value : 0.000


# 단순선형회귀 1 실습

In [64]:
df_raw = pd.read_csv("/home/piai/bigdata/data/correaltion.csv", engine = 'python')
df_raw.head()

strength = df_raw['strength']
b_time= df_raw['b_time']

b_time = sm.add_constant(b_time)
model = sm.OLS(strength,b_time)
result = model.fit()
print(result.summary())

# R-squared 값이 0.933으로 데이터분석모델이 적합하다는것을 알 수 있다.
# 또한 strength = 44.5520*b_time + 2.1034 라는 수식을 얻을 수 있다.

                            OLS Regression Results                            
Dep. Variable:               strength   R-squared:                       0.933
Model:                            OLS   Adj. R-squared:                  0.932
Method:                 Least Squares   F-statistic:                     1169.
Date:                Wed, 11 Nov 2020   Prob (F-statistic):           4.60e-51
Time:                        19:54:26   Log-Likelihood:                -107.75
No. Observations:                  86   AIC:                             219.5
Df Residuals:                      84   BIC:                             224.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.1034      0.885      2.377      0.0

# 단순선형회귀 2 

In [66]:
df_raw = pd.read_csv("/home/piai/bigdata/data/correaltion.csv", engine = 'python')
df_raw.head()

reg_model = smf.ols("strength ~ Oven_TMP", data = df_raw)
reg_result = reg_model.fit()

print(reg_result.summary())

#
#회귀 분석식 R-squared값이 0.001로 분석모델이 적합하지 않다.
# 회귀 식은 strength = 30.4190 + 0.0056*Oven_TMP 이다




                            OLS Regression Results                            
Dep. Variable:               strength   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                 -0.011
Method:                 Least Squares   F-statistic:                    0.1136
Date:                Wed, 11 Nov 2020   Prob (F-statistic):              0.737
Time:                        19:55:43   Log-Likelihood:                -223.88
No. Observations:                  86   AIC:                             451.8
Df Residuals:                      84   BIC:                             456.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     30.4190      5.271      5.771      0.0